name: aerospike-client-python

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-python:manylinux

build:
  - name: build
    script:
      - make -C aerospike-client-c
      - scripts/manylinuxbuild.sh
    artifact:
      - /work/wheels/*.whl
