name: aerospike-client-python

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-python:manylinux2014

build:
  - name: build
    script:
      - scripts/manylinux2014build.sh
    artifact:
      - /work/wheels/*.whl
